Greetings = [

'Politics!',
'Squidword!',
'Steven Wright',
'See you Monday!',
'Stewart Francis.',
'Knock, knock. A: Come in!',
'Venison\'s dear isn\'t it?',
'A good pun is it\'s own reword.',
'Has someone heard from Lillian?',
'I saw a stationary store moves.',
'There’s no silent p in swimming.',
'I have a CD Burner…my fireplace.',
'I heard it is still hot in Texas.',
'Did I already do my deja vu joke?',
'A well done medium steak is rare.',
'If your computer has a virus scan it.',
'I\'m so bright my mom calls me “son”.',
'Boycott shampoo! Demand the real poo!',
'I have a cat in my pocket… Just kitten.',
'A one armed guy goes to a 2nd hand shop.',
'If I agreed with you we\'d both be wrong.',
'Where there\'s a will, there are relatives.',
'The numbers 19 and 20 got into a fight. 21.',
'The advantage of easy origami is two-folded.',
'Toilet Stolen: Police have nothing to go on.',
'I would give my right arm to be ambidextrous.',
'Hedgehogs, why can\'t they just share the hedge?',
'Roses are grey, Violets are grey, and I am a dog.',
'Time flies like an arrow; fruit flies like a banana.',
'The crows seemed to be calling his name, thought Caw.',
'Two wrongs don\'t make a right but three lefts do.',
'Change is inevitable, except from a vending machine.',
'It\'s a small world but I wouldn\'t want to paint it.',
'On the other hand, you have different fingers.',
'I know a great knock-knock joke, but you have to start.',
'A termite walks into a bar and asks “Is the bartender here?”',
'Support bacteria. They are the only culture some people have.',
'I farted in an elevator once, it was wrong on so many levels.',
'Cut that pizza into 4 slices… I\'m not hungry enough to eat 6.',
'Working in a mirror factory is something I can totally see myself doing',
'If i had a dollar for every brain you didn\'t have, I\'d have one dollar',
'Plate of spaghetti walks up to a bar, bartender says “we don\'t serve food here.”',
'The early bird may catch the worm, but it’s the second mouse that gets the cheese.',
'I used to play the trombone, but I\'ve let it slide.',
'Two drums and a cymbal fall off a cliff. A: Ba-dun TSSH',
'Is a hippopotamus a hippopotamus or just a cool opotamus?',
'If at first you don\'t succeed, skydiving\'s not for you.',
'1: Have you seen my henlay? 2: What\'s a Henlay? 1: Eggs!',
'Two peanuts are walking down the street. One was a salted.',
'I fought a bear with a knife once. The bear had the knife.',
'I didn\'t like my haircut at first, but it\'s growing on me.',
'Snakes don\'t have arms, that\'s why they don\'t wear vests.',
'Mountains aren\'t just funny, they\'re hill areas (hillarious)',
'When I found out the toaster wasn\'t waterproof, I was shocked.',
'Corduroy pillows….they\'re making headlines all over the world.',
'I heard that\'s cloudy with possibilities of scanning all day.',
'War doesn\'t determine who is right, it determines who is left.',
'Don\'t sweat the petty things, and don\'t pet the sweaty things.',
'I have a stepladder because my real ladder left when I was a kid.',
'I think it\'s wrong that only one company makes the game Monopoly.',
'Roses are red, Violets are blue, I am bad at rhyming, Refrigerator.',
'I sold my vacuum the other day. All it was doing was collecting dust.',
'Parallel lines have so much in common. It\'s a shame they will never meet.',
'You\'re going to have to start calling me “butter” because I\'m on a roll.',
'It\'s one of those situations where you thought it was a booger, but it snot.',
'I used to work in a calendar factory but I got fired for taking a few days off.',
'I told my wife she was drawing her eyebrows too high. She looked at me surprised.',
'1: Have you seen my updog? 2: What is updog? 1: Oh nothing much. What new with you?',
'I quit my job at the helium balloon factory, I refuse to be spoken to in that tone.',
'1: "This computer will cut your workload by 50%". 2: "Great!! I\'ll take two of them"',
'Portholes are round so that if they break, water doesn\'t hit you square in the face.',
'I needed a password with eight characters, so I chose Snow White and the Seven Dwarves.',
'My friends and I were playing poker with a giant set of cards. It was kind of a big deal.',
'I am hardly ever wrong. Except this one time, when I thought I was wrong, but I was wrong.',
'Two fish in a tank. One turns to the other and asks “Do you know how to drive this thing?”',
'I used to work in an orange juice factory but I got fired because I couldn\'t concentrate.',
'I used to play sports. Then I realized you could BUY trophies. Now I\'m good at everything.',
'A 3-legged dog hops into a saloon and proclaims, "I\'m looking for the man who shot my paw!"',
'At what age is it appropriate to tell my dog/cat that they are adopted?',
'Roses are red, Violets are blue. Oh wait, no they\'re not, They’re violet!',
'A magician was driving down the road when suddenly he turned into a driveway.',
'I entered 10 puns into a joke contest hoping one would win. No pun in ten did.',
'Did you hear about the claustrophobic astronaut? He just needed a little space.',
'I used to be in a band, we were called ‘lost dog’. You probably saw our posters.',
'Never trust math teachers who use graph paper. They\'re always plotting something.',
'If you lend someone $20, and never see that person again; it was probably worth it.',
'I got my hair highlighted, because I felt some strands were more important than others.',
'Teacher: What can you tell me about the Dead Sea? Student: I didn\'t even know it was sick!',
'There are 10 types of people in the world - those who understand binary, and those who don\'t.',
'Saw a man in a field tending to a little more than 3 sheep. Thought to myself “shepherd\'s pi”.',
'1: Do you know where I can get some snoo? 2: What\'s snoo? 1: Oh nothing much. What new with you?',
'And then there was the agnostic dyslexic insomniac who stayed up all night wondering if there really is a dog.',
'Yesterday I saw a guy spill all his Scrabble letters on the road. I asked him, “What\'s the word on the street?”',
'Two windmills are standing in a wind farm. One asks, “What\'s your favorite type of music?” The other says, “I\'m a big metal fan.”',
'A rubber band pistol was confiscated in algebra class; it was a weapon of math disruption. *Requires a specific cadence to make authentic and appealing*',

'Q: Why do we seagulls fly over the sea? A: Because if they flew over the bay they would be called bagels!',
'Q: What did the digital clock say to the grandfather clock? A: Look Grandpa! No hands!',
'Q: How do you make an egg roll? A: You push it!',
'Q: How many tickles does it take to make an octopus laugh? A: Ten Tickles!',
'Q: What goes zzub zzub? A: A bee flying backwards.',
'Q: What\'s the capital of Washington? A: The W!',
'Q: Why did the baby cookie cry? A: Because his mother was a wafer so long.',
'Q: What is the difference between a blue fridge falling of a cliff, and a yellow one? A: The blue fridge is an appliance and the yellow one is a number.',
'Q: What is the difference between a blue fridge falling of a cliff, and a yellow one? A: The yellow one isn\'t falling of a cliff.',
'Q: When is a door not a door? A: When it is a jar.',
'Q: What is green and has four wheels? A: Grass, silly! I was just kidding about the wheels. *Requires a specific cadence to make authentic and appealing*',
'Q: When is a lumberjack\'s birthday? A: SepTIMBERRRRRRRR!',
'Q: Where does the three-legged horse live? A: In the unstable.',
'Q: What\'s brown and sticky? A: A stick!',
'Q: Did you hear about the fire at the circus? A: The heat was in tents!',
'Q: Have you seen the elephant hiding? A: Of course not, he’s hiding.',
'Q: How does Moses make his coffee? A: Hebrews it!',
'Q: Why do cows wear bells? A: Because their horns don\'t work.',
'Q: What is it about being blind, that makes you walk the dog all the time?',
'Q: Why is it called tourist season if we can\'t shoot them?',
'Q: Why did Snoop Dogg buy an umbrella? A: ForDrizzle',
'Q: What\'s invisible and smells like a carrot? A: A rabbit\'s toot.',
'Q: What do you call someone who doesn\'t fart in public? A: A private tooter!',
'Q: What kind of projection do 3 out of 4 ear, nose, and throat specialists prefer? A: A sinus-oidal map projection.',
'Q: Why do paper maps never win at poker? A: Because they always fold.',
'Q: What do you call a map showing the heights of leafy-stemmed perennial herbs measured in centimeters? A: A daisy metric map',
'Q: What is smarter, longitude or latitude? A: Longitude, because it has 360 degrees',
'Q: What projection is used to map the distribution of chocolate lovers? A: The Bonne-Bonne (bon bon) projection.',
'Q: Why do senior military officials like small scale maps? A: Because they have been GENERAL-ized.',
'Q: Why are maps like fish? A: They both have scales.',
'Q: Where to lines of eQual pressure go to relax? A: In ISO - bars (In Search Of isobars)',
'Q: Why was the map gesturing wildly? A: It was an animated map.',
'Q: Why was longitude boiling mad? A: Because it was 360 degrees.',
'Q: What do John Wayne and a map key have in common? A: Both are legends.',
'Q: Why did the cartographer put a band-aid on the map? A: Because it had a bleeding edge.',
'Q: What kind of sunglasses do physical relief maps wear? A: Hypsometric tints.',
'Q: Why couldn\'t Mark McGwire reach first after hitting his 62nd home run? A: He didn\'t have a base map.',
'Q: Why did the equator win the MVP (most valuable parallel) award at the Latitude Super Bowl? A: Because it was a great circle.',
'Q: What is the tidiest element on a map? A: The neatline.',
'Q: What do you call a USGS quadrangle with green water, blue forests, and all the names spelled backwards? A: A topo-illogical map.',
'Q: What did the mapmaker send his sweetheart on Valentine\'s Day? A: A dozen compass roses.',
'Q: What do a row of Bacardi bottles and a loxodrome have in common? A: Both are rum (rhumb) lines.',
'Q: Why didn\'t true north date magnetic north? A: She didn\'t like his bearing.',
'Q: What do you get when you cross a cowboy with a mapmaker? A: A cow-tographer.',
'Q: Why did not the map have any meridians? A: It was a map of a parallel universe.',
'Q: Why does west longitude need to be cheered up? A: Because it is always negative.',
'Q: What do you call a map guide to Alcatraz? A: A con-tour map.',
'Q: “What\'s up?” A: A two letter word.',
'Q: Why weren\'t there any parallels on the map? A: Because the cartographer didn\'t have any latitude in his map design.',
'Q: What do you call an Alligator in a vest? A: An Investigator.',
'Q: How can you tell if a map was made by a troll? A: It is in the gnome-onic (gnomonic) projection.',
'Q: What kind of maps do spiders make? A: Web-based maps.',
'Q: What did the green grape say to the purple grape? A: BREATHE!!',
'Q: What do you call the Queue of foreign couples outside the Hard Rock Cafe? A: The international date line.',
'Q: Why didn\'t the map projection finish his speech? A: He was interrupted.',
'Q: A Mercator, Lambert Conformal, and Homolosine projection met Saint Peter at the Pearly Gates. Only the Homolsine Projection went on to heaven. Why? A: It was the only Good(e) projection.',
'Q: Why do soldiers study their maps at stop lights? A: Because their maps are red-light readable.',
'Q: How do maps get around London? A: They take the map tube.',
'Q: How do you clean a nautical chart? A: You give it an iso-bath (isobath).',
'Q: Why did the cartographer put the projection in a hangar? A: It was a plane projection.',
'Q: What map element plays in the band? A: The symbols (cymbals).',
'Q: Did you hear about the map that was mugged? A: It was rolled by the map librarian.',
'Q: What is a nautical chart\'s best pitch? A: The depth curve.',
'Q: Why was the map twitching? A: It had a nervous tic.',
'Q: Why did the map crash? A: It lost its control.',
'Q: What did Delaware? A: A New Jersey.',
'Q: What do you call a Dothraki mathematician? A: Khal Culator!',
'Q: What projection do birds use to track their migration? A: A robins-son (Robinson) projection.',
'Q: What kind of map plays CDs? A: A stereo map.',
'Q: What\'s round at each end and high in the middle? A: Ohio',
'Q: Why is a lifeguard like a polar stereographic projection? A: The lifeguard is a tan gent and the polar stereographic projection is tangent.',
'Q: Why did the innocent map go to jail? A: It was framed by the neatline.',
'Q: What projection do lost sheep use to find their way home? A: The Lamb-ert Conic Conformal projection.',
'Q: Why don\'t cartography librarians wear high heels? A: They prefer map flats.',
'Q: What is the difference between a tub full of freezing water and a depth contour? A: One is an icy bath and the other is an isobath.',
'Q: How do maps comb their hair? A: They use a geographic brush.',
'Q: Why is the Jenks classification system like an orthopedic surgeon? A: They both deal with natural breaks.',
'Q: Why didn\'t the marginalia go to the dance? A: It didn\'t have a date.',
'Q: Why was the globe rated "R"? A: Because of its gore. (In earlier times, a map that was pasted on the globe consisted of a number of tapered strips, called gores.)',
'Q: What is the difference between a black tie dinner for prisoners and a projection showing true shape? A: One is a con formal and the other is conformal.',
'Q: What kind of contours can see in the dark? A: Illuminated contours.',
'Q: Why couldn\'t Mark McGwire reach first after hitting his 62nd home run? A: He didn\'t have a base map.',
'Q: What do you call a map of outhouses in the woods? A: A shaded relief map.',
'Q: How can you tell if a map was made by a troll? A: It is in the gnome-onic (gnomonic) projection.',
'Q: What kind of maps do spiders make? A: Web-based maps.',
'Q: What do you call the Queue of foreign couples outside the Hard Rock Cafe? A: The international date line.',
'Q: Why didn\'t the map projection finish his speech? A: He was interrupted.',
'Q: A Mercator, Lambert Conformal, and Homolosine projection met Saint Peter at the Pearly Gates. Only the Homolsine Projection went on to heaven. Why? A: It was the only Good(e) projection.',
'Q: Why do soldiers study their maps at stop lights? A: Because their maps are red-light readable.',
'Q: How do maps get around London? A: They take the map tube.',
'Q: How do you clean a nautical chart? A: You give it an iso-bath (isobath).',
'Q: Why did the cartographer put the projection in a hangar? A: It was a plane projection.',
'Q: What map element plays in the band? A: The symbols (cymbals).',
'Q: Did you hear about the map that was mugged? A: It was rolled by the map librarian.',
'Q: What is a nautical chart\'s best pitch? A: The depth curve.',
'Q: Why was the map twitching? A: It had a nervous tic.',
'Q: Why did the map crash? A: It lost its control.',
'Q: What do you call the little rivers that flow into the Nile? A: Juveniles!',
'Q: Why did the dot go to college? A: To become a graduated symbol!',
'Q: What projection do birds use to track their migration? A: A robins-son (Robinson) projection.',
'Q: What kind of map plays CD\'s? A: A stereo map.',
'Q: Why is a lifeguard like a polar stereographic projection? A: The lifeguard is a tan gent and the polar stereographic projection is tangent.',
'Q: Why did the innocent map go to jail? A: It was framed by the neatline.',
'Q: What projection do lost sheep use to find their way home? A: The Lamb-ert Conic Conformal projection.',
'Q: Why don\'t cartography librarians wear high heels? A: They prefer map flats.',
'Q: What is the difference between a tub full of freezing water and a depth contour? A: One is an icy bath and the other is an isobath.',
'Q: How do maps comb their hair? A: They use a geographic brush.',
'Q: Why is the Jenks classification system like an orthopedic surgeon? A: They both deal with natural breaks.',
'Q: Why didn\'t the marginalia go to the dance? A: It didn\'t have a date.',
'Q: Why was the globe rated "R"? A: Because of its gore. (In earlier times, a map that was pasted on the globe consisted of a number of tapered strips, called gores.)',
'Q: What is the difference between a black tie dinner for prisoners and a projection showing true shape? A: One is a con formal and the other is conformal.',
'Q: What kind of contours can see in the dark? A: Illuminated contours.',
'Q: Why do we tell actors to “break a leg?” A: Because every play has a cast.',
'Q: What did the left eye say to the right eye? A: Between you and me, something smells.',
'Q: What did the buffalo say when his son left for college? A: Bison',
'Q: Why did the frog take the bus to work today? A: His car got toad away.',
'Q: What\'s Forest Gump\'s password? A: 1Forest1',
'Q: What breed of dog can jump higher than buildings? A: Any dog, because buildings can\'t jump.',
'Q: Why did the M&M go to school? A: It wanted to be a Smartie.',
'Q: Why did the nurse need a red pen at work? A: In case she needed to draw blood.',
'Q: Why did the math textbook visit the guidance counselor? A: It needed help figuring out its problems.',
'Q: What is an astronaut\'s favorite part on a computer? A: The space bar.',
'Q: What do you call a fake noodle? A: An impasta',
'Q: Why is Peter Pan flying all the time? A: He Neverlands!',
'Q: How did the geography student drown? A: His grades were below C-level.',
'Q: What do you call an alligator in a vest? A: An in-vest-igator.',
'Q: What city always cheats at exams? A: Peking.',
'Q: Why is Cinderella so bad at soccer? A: Because she always runs away from the ball!',
'Q: How do geographers find the girl they are going to marry? A: They datum.',

];